FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    url(r'^(?P<an>\d+)?(/(?P<semaine>\d+))?$', views.edt, name="edt"),
    url(r'^tv/(?P<semaine>\d+)?(/(?P<an>\d+))?$', views.edt_light, name="edt_light"),
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),
    url(r'^contact$', views.contact, name="contact"),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    url(r'^fetch_cours_pl/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pl, name="fetch_cours_pl"),
    url(r'^fetch_cours_pp/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pp, name="fetch_cours_pp"),
    url(r'^fetch_dispos/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_dispos, name="fetch_dispos"),
    url(r'^fetch_stype/$', views.fetch_stype, name="fetch_stype"),
    url(r'^fetch_decale/$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_bknews/$', views.fetch_bknews, name="fetch_bknews"),
    url(r'^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_unavailable_rooms, name="fetch_unavailable_rooms"),
    url(r'^fetch_all_tutors/$', views.fetch_all_tutors, name="fetch_all_tutors"),

    # from screen to db
    url(r'^change_edt/$', views.edt_changes, name="edt_changes"),
    url(r'^change_dispos/$', views.dispos_changes, name="dispos_changes"),
    url(r'^change_decale/$', views.decale_changes, name="decale_changes"),


    # predefined
    # ------------
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

FlOpEDT/people/urls.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from people.student import AddStudent, ChangeStudent
from people.tutor import AddFullStaffTutor, AddSupplyStaffTutor, AddBIATOSTutor
from people.tutor import ChangeFullStaffTutor, ChangeSupplyStaffTutor, ChangeBIATOSTutor
from django.contrib.auth import views as auth_views
from . import views

app_name="people"

urlpatterns = [
#    url(r'^login', views.login, name="login"),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='people/login.html'),
        name='login'),
    url(r'^logout/$',
        auth_views.LogoutView.as_view( next_page= '/'),
        name='logout'),
    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view( template_name='people/password_reset_form.html', email_template_name='people/password_reset_email.html',
         subject_template_name='people/password_reset_subject.txt',
         success_url='people:password_reset_done'),
        name='password_reset'),
    url(r'^pwd-reset-done/$',
        auth_views.PasswordResetDoneView.as_view( template_name='people/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(template_name='people/password_change_form.html',
         success_url='people:password_change_done'),
        name='password_change'),
    url(r'^pwd-chg-done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='people/password_change_done.html'),
        name='password_change_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view( template_name='people/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^add/some/(?P<kind>[A-Za-z]*)$',
        views.redirect_add_people_kind,
        name="add_redirect"),
    url(r'^add/student/$',
        AddStudent.as_view(),
        name="add_student"),
    url(r'^add/fullstaff/$',
        AddFullStaffTutor.as_view(),
        name="add_fullstaff"),
    url(r'^add/supplystaff/$',
        AddSupplyStaffTutor.as_view(),
        name="add_supplystaff"),
    url(r'^add/biatos/$',
        AddBIATOSTutor.as_view(),
        name="add_BIATOS"),
    url(r'^change/some/$',
        views.redirect_change_people_kind,
        name="change_redirect"),
    url(r'^change/student/$',
        ChangeStudent.as_view(),
        name="change_student"),
    url(r'^change/fullstaff/$',
        ChangeFullStaffTutor.as_view(),
        name="change_fullstaff"),
    url(r'^change/supplystaff/$',
        ChangeSupplyStaffTutor.as_view(),
        name="change_supplystaff"),
    url(r'^change/biatos/$',
        ChangeBIATOSTutor.as_view(),
        name="change_BIATOS"),
    ]

FlOpEDT/quote/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="quote"

urlpatterns = [
    # directly reachable by users
    # ----------------------------
    url(r'^proposer$', views.submit, name="submission"),
    # url(r'^moderer$', views.moderate, name="moderation"),
    # fetch 
    # ----------------------------
    url(r'^fetch$', views.fetch_quote, name="fetch_quote"),
    
]

FlOpEDT/base/forms.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django import forms
from people.models import Tutor, FullStaff


class ContactForm(forms.Form):
    sender = forms.EmailField(label='Votre adresse mail :')
    recipient = forms.CharField(
        label='Destinataire :',
        max_length=4,
        help_text="Acronyme : 4 caractères max")
    subject = forms.CharField(
        label='Sujet du mail :',
        max_length=100,
        help_text="100 caractères max")
    message = forms.CharField(label='Corps du mail :',
                              max_length=2000,
                              widget=forms.Textarea())

    def clean_recipient(self):
        recipient = self.cleaned_data['recipient']
        if not Tutor.objects.filter(username=recipient).exists():
            raise forms.ValidationError("Cette personne n'existe pas.")
        return recipient

FlOpEDT/base/templates/base/aide.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static "base/better.css" %}"/>

<div id="tools-main" style="padding:10px;">

    <h4>Modification de salle</h4>
    <p>Click droit sur le cours en question. Ne pas oublier de valider tout changement.</p>
    
    <h4>Création d'un compte</h4>
    <p>Aller dans <a href="{% url "people:login" %}">Se connecter</a>, puis sélectionner le statut.</p>
    
    <h4>Modification d'un compte</h4>
    <p>Cliquer sur son pseudo en haut de la page.</p>
    
    <h5>Modification de mot de passe</h5>
    <p><a href="{% url 'people:password_change' %}">Ici</a>.</p>

    <h4>Oubli de mot de passe</h4>
    <p><a href="{% url 'people:password_reset' %}">Ici</a>, ou "Se connecter" en haut de page.</p>
    
    <h4>Fonctionnement de la saisie des disponibilités</h4>
    <p>Au moment de la génération de l'emploi du temps d'une semaine donnée, si aucune disponibilité n'est renseignée pour cette semaine, la semaine type définit les disponibilités.</p>

</div>
{% endblock %}

FlOpEDT/base/templates/base/contact.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% block title %} EDT {% endblock %}
{% block content %}
<font color="black">
<form method="post" novalidate>
  {% csrf_token %}
  <table cellpadding="10">
    {{ form }}
  </table>
  <button type="submit">Envoyer</button>
  <div> {{ ack }} </div>
  <div> <br/><br/> </div>
</form>
</font>
{% endblock %}

FlOpEDT/base/templates/base/show-edt-light.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->


{% csrf_token %}


<title>EdT</title>
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/header.css" %}"/>
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
  <script src="{% static "base/d3.v4.min.js" %}"></script>
  <script src="{% static 'base/jquery.min.js' %}"></script>
  <!-- script src="https://d3js.org/d3.v4.min.js"></script -->
  <script>
    var groupes_fi = "{% static "base/groups.json" %}";
    var url_cours_pl = "{% url "base:fetch_cours_pl" 0 0 0 %}";
    url_cours_pl = url_cours_pl.slice(0,-5);
    var url_dispos = "{% url "base:fetch_dispos" 0 0 %}";
    url_dispos = url_dispos.slice(0,-3);
    var url_login = "{% url "people:login"%}";
    var url_edt = "{% url "base:edt"%}";
    var url_edt_changes = "{% url "base:edt_changes"%}";
    var url_dispos_changes = "{% url "base:dispos_changes"%}";
    var url_fetch_stype = "{% url "base:fetch_stype" %}"; 
    var url_bknews = "{% url "base:fetch_bknews" %}"; 

    var semaine_an_list = {{ all_weeks|safe }};
    var jours_list = {{ jours|safe }};
    var semaine_init = +"{{ semaine }}";
    var an_init = +"{{ an }}";
    var une_salle = "{{ une_salle }}";

    
    var usna = "{{ user.username }}" ;
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    var tv_svg_h = "{{ tv_svg_h }}" ;
    var tv_svg_w = "{{ tv_svg_w }}" ;
    var tv_gp_h = "{{ tv_gp_h }}" ;
    var tv_gp_w = "{{ tv_gp_w }}" ;
    var promo_init = "{{ promo }}";
    var gp_init = "";
    var tv_svg_top_m = "{{ tv_svg_top_m }}" ;
    var logged_usr = {};
    
  </script>
  </script>
<body>
</body>
  <script type='text/javascript' src="{% static "base/variables.js" %}?3"></script>
  <script type='text/javascript' src="{% static 'base/week_change.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/transformation.js' %}"></script>
  <script type='text/javascript' src="{% static "base/creation.js" %}?3"></script>
  <script type='text/javascript' src="{% static 'base/action.js' %}"></script>
  <script type='text/javascript' src="{% static "base/update.js" %}?3"></script>
  <script type='text/javascript' src="{% static "base/edt-only.js" %}?3"></script>
    

{% endblock %}

FlOpEDT/base/templates/base/show-edt.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% csrf_token %}

{% block title %} EDT {% endblock %}
{% block content %}


{% load static %}
<link rel="stylesheet" href="{% static 'base/better.css' %}?2"/>
  <script src="{% static 'base/d3.v4.min.js' %}"></script>
  <!-- script src='https://d3js.org/d3.v4.min.js'></script -->
  <script>
    var groupes_fi = "{% static 'base/groups.json' %}";
    var rooms_fi = "{% static 'base/rooms.json' %}";

    var url_cours_pl = "{% url "base:fetch_cours_pl" 0 0 0 %}";
    url_cours_pl = url_cours_pl.slice(0,-5);
    var url_cours_pp = "{% url "base:fetch_cours_pp" 0 0 0 %}";
    url_cours_pp = url_cours_pp.slice(0,-5);
    var url_dispos = "{% url "base:fetch_dispos" 0 0 %}";
    url_dispos = url_dispos.slice(0,-3);
    var url_unavailable_rooms = "{% url "base:fetch_unavailable_rooms" 0 0 %}";
    url_unavailable_rooms = url_unavailable_rooms.slice(0,-3);
    var url_all_tutors = "{% url "base:fetch_all_tutors" %}";
    var url_login = "{% url "people:login"%}";
    var url_edt = "{% url "base:edt"%}";
    var url_edt_changes = "{% url "base:edt_changes"%}";
    var url_dispos_changes = "{% url "base:dispos_changes"%}";
    var url_fetch_stype = "{% url "base:fetch_stype" %}"; 
    var url_bknews = "{% url "base:fetch_bknews" %}"; 
    var url_quote = "{% url "quote:fetch_quote" %}"; 

    var semaine_an_list = {{ all_weeks|safe }};
    var jours_list = {{ jours|safe }};
    var semaine_init = +"{{ semaine }}";
    var an_init = +"{{ an }}";

    var promo_init = +"{{ promo }}";
    var num_copie = +"{{ copie }}";
    var gp_init = "{{ gp }}";

//    var cours_pp = {{ cpp|safe }};

    var une_salle = "{{ une_salle }}";
    
    var logged_usr = {nom:"{{ name_usr }}", rights: "{{ rights_usr }}"};

    var splash_id = "{{ splash_id }}" ; 

    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
  </script>

  <!--   <script type='text/javascript' src="{% static "base/better.js" %}"></script>-->
  <script type='text/javascript' src="{% static 'base/variables.js' %}?2"></script>
  <script type='text/javascript' src="{% static 'base/week_change.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/transformation.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/creation.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/action.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/update.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/all.js' %}"></script>
    

{% endblock %}

FlOpEDT/base/templates/base/show-stype.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing -->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% extends "base.html" %}

{% csrf_token %}



{% block title %} EDT {% endblock %}
{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static "base/better.css" %}"/>
  <script src="{% static "base/d3.v4.min.js" %}"></script>
  <!-- script src="https://d3js.org/d3.v4.min.js"></script -->
  <script>
    var url_fetch_stype = "{% url "base:fetch_stype" %}"; 
    var url_stype = "{% url "base:stype" %}"; 
    var url_dispos_changes = "{% url "base:dispos_changes"%}";
    var logged_usr = {nom:"{{ name_usr }}", rights: -1};
    var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
    var url_login = "{% url "people:login"%}";
    var annee_courante = "{{ annee_courante }}" ;
  </script>
  </script>
<body>
    <!--    <div id="option">
      <label>
      <input name="dispoBox" 
             type="checkbox" />
      Dispos
      </label>
      <button onclick="fetchjson()">Json</button>
      <button onclick="fetchcsv()">CSV</button>
      <button onclick="fetch_dispo()">Dispos</button>
    </div>-->
    <div  id="tools-main" style="width: 100%; overflow: hidden;">
      <div id="svg" style="width: 680px; float: left;"></div>
      <div style="margin-left: 700px;">
	<form style="white-space: nowrap;" name="app" action="javascript:apply_stype_from_button(false)">
	  <fieldset>
	    <legend>Semaines particulières</legend>
	    Appliquer la configuration ci-contre<br/>
	    de la semaine
	    <input type="number" name="se_deb" style="width: 40px" value="{{ date_deb.semaine }}" min="1" max="53">, année
	    <input type="number" name="an_deb" style="width: 60px" value="{{ date_deb.an }}" min="{{annee_courante}}" max="{{annee_courante|add:"1"}}"></br>
	    à la semaine
	    <input type="number" name="se_fin" style="width: 40px" value="{{ date_fin.semaine }}" min="1" max="53">, année
	    <input type="number" name="an_fin" style="width: 60px" value="{{ date_fin.an }}" min="{{annee_courante}}" max="{{annee_courante|add:"1"}}"></br></br>
	    <input type="submit" name="apply" value="Appliquer">
	  </fieldset></br></br>
	</form>
	<fieldset>
	  <legend>Semaine type</legend>
	  <form style="white-space: nowrap;" name="sav"  action="javascript:apply_stype_from_button(true)">
	    Redéfinir ma semaine type<br/>
</br>
	    <input type="submit" name="save" value="Sauvegarder"></br>	  </fieldset>
	</form></br>
	<!--{% if err %}<p><strong>{{ err }}</strong></p>{% endif %}
	  -->
	<span id="ack"></span>
      </div>
    </div>
</body>
  <script type='text/javascript' src="{% static 'base/week_change.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/transformation.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/creation.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/action.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/update.js' %}"></script>
  <script type='text/javascript' src="{% static 'base/variables.js' %}?2"></script>
<script type='text/javascript' src="{% static "base/stype.js" %}"></script>

{% endblock %}