FlOpEDT/base/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

app_name="base"

urlpatterns = [
    # favicon
    # ----------------------------
    url(views.fav_regexp,
        views.favicon,
        name="favicon"),

    # directly reachable by users
    # ----------------------------
    url(r'^(?P<an>\d+)?(/(?P<semaine>\d+))?$', views.edt, name="edt"),
    url(r'^tv/(?P<semaine>\d+)?(/(?P<an>\d+))?$', views.edt_light, name="edt_light"),
    url(r'^semaine-type$', views.stype, name="stype"),
    url(r'^aide$', views.aide, name="aide"),
    url(r'^decale$', views.decale, name="decale"),
    url(r'^contact$', views.contact, name="contact"),

    # exchanges with the db via django
    # ---------------------------------

    # from db to screen
    url(r'^fetch_cours_pl/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pl, name="fetch_cours_pl"),
    url(r'^fetch_cours_pp/(?P<year>\d+)/(?P<week>\d+)/(?P<num_copy>\d+)$', views.fetch_cours_pp, name="fetch_cours_pp"),
    url(r'^fetch_dispos/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_dispos, name="fetch_dispos"),
    url(r'^fetch_stype/$', views.fetch_stype, name="fetch_stype"),
    url(r'^fetch_decale/$', views.fetch_decale, name="fetch_decale"),
    url(r'^fetch_bknews/$', views.fetch_bknews, name="fetch_bknews"),
    url(r'^fetch_unavailable_rooms/(?P<year>\d+)/(?P<week>\d+)$', views.fetch_unavailable_rooms, name="fetch_unavailable_rooms"),
    url(r'^fetch_all_tutors/$', views.fetch_all_tutors, name="fetch_all_tutors"),

    # from screen to db
    url(r'^change_edt/$', views.edt_changes, name="edt_changes"),
    url(r'^change_dispos/$', views.dispos_changes, name="dispos_changes"),
    url(r'^change_decale/$', views.decale_changes, name="decale_changes"),


    # predefined
    # ------------
]

# https://pypi.python.org/pypi/django-live-log
# https://github.com/abdullatheef/django_live_log

FlOpEDT/people/urls.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include
from people.student import AddStudent, ChangeStudent
from people.tutor import AddFullStaffTutor, AddSupplyStaffTutor, AddBIATOSTutor
from people.tutor import ChangeFullStaffTutor, ChangeSupplyStaffTutor, ChangeBIATOSTutor
from django.contrib.auth import views as auth_views
from . import views

app_name="people"

urlpatterns = [
#    url(r'^login', views.login, name="login"),
    url(r'^login/$',
        auth_views.LoginView.as_view(template_name='people/login.html'),
        name='login'),
    url(r'^logout/$',
        auth_views.LogoutView.as_view( next_page= '/'),
        name='logout'),
    url(r'^password-reset/$',
        auth_views.PasswordResetView.as_view( template_name='people/password_reset_form.html', email_template_name='people/password_reset_email.html',
         subject_template_name='people/password_reset_subject.txt',
         success_url='people:password_reset_done'),
        name='password_reset'),
    url(r'^pwd-reset-done/$',
        auth_views.PasswordResetDoneView.as_view( template_name='people/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^password-change/$',
        auth_views.PasswordChangeView.as_view(template_name='people/password_change_form.html',
         success_url='people:password_change_done'),
        name='password_change'),
    url(r'^pwd-chg-done/$',
        auth_views.PasswordChangeDoneView.as_view(template_name='people/password_change_done.html'),
        name='password_change_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
        r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view( template_name='people/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^add/some/(?P<kind>[A-Za-z]*)$',
        views.redirect_add_people_kind,
        name="add_redirect"),
    url(r'^add/student/$',
        AddStudent.as_view(),
        name="add_student"),
    url(r'^add/fullstaff/$',
        AddFullStaffTutor.as_view(),
        name="add_fullstaff"),
    url(r'^add/supplystaff/$',
        AddSupplyStaffTutor.as_view(),
        name="add_supplystaff"),
    url(r'^add/biatos/$',
        AddBIATOSTutor.as_view(),
        name="add_BIATOS"),
    url(r'^change/some/$',
        views.redirect_change_people_kind,
        name="change_redirect"),
    url(r'^change/student/$',
        ChangeStudent.as_view(),
        name="change_student"),
    url(r'^change/fullstaff/$',
        ChangeFullStaffTutor.as_view(),
        name="change_fullstaff"),
    url(r'^change/supplystaff/$',
        ChangeSupplyStaffTutor.as_view(),
        name="change_supplystaff"),
    url(r'^change/biatos/$',
        ChangeBIATOSTutor.as_view(),
        name="change_BIATOS"),
    ]

FlOpEDT/solve_board/urls.py
# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django.conf.urls import url, include

from solve_board import views

app_name="solve_board"

urlpatterns = [
    url(r'^main/$', views.main_board, name="main_board"),
#    url(r'^run/(?P<timestamp>[0-9-]+)?$', views.run, name="run"),
]

FlOpEDT/base/forms.py
# -*- coding: utf-8 -*-

# This file is part of the FlOpEDT/FlOpScheduler project.
# Copyright (c) 2017
# Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public
# License along with this program. If not, see
# <http://www.gnu.org/licenses/>.
# 
# You can be released from the requirements of the license by purchasing
# a commercial license. Buying such a license is mandatory as soon as
# you develop activities involving the FlOpEDT/FlOpScheduler software
# without disclosing the source code of your own applications.

from django import forms
from people.models import Tutor, FullStaff


class ContactForm(forms.Form):
    sender = forms.EmailField(label='Votre adresse mail :')
    recipient = forms.CharField(
        label='Destinataire :',
        max_length=4,
        help_text="Acronyme : 4 caractères max")
    subject = forms.CharField(
        label='Sujet du mail :',
        max_length=100,
        help_text="100 caractères max")
    message = forms.CharField(label='Corps du mail :',
                              max_length=2000,
                              widget=forms.Textarea())

    def clean_recipient(self):
        recipient = self.cleaned_data['recipient']
        if not Tutor.objects.filter(username=recipient).exists():
            raise forms.ValidationError("Cette personne n'existe pas.")
        return recipient

FlOpEDT/templates/base.html
<!-- This file is part of the FlOpEDT/FlOpScheduler project.               -->
<!-- Copyright (c) 2017                                                    -->
<!-- Authors: Iulian Ober, Paul Renaud-Goud, Pablo Seban, et al.           -->
<!--                                                                       -->
<!-- This program is free software: you can redistribute it and/or modify  -->
<!-- it under the terms of the GNU Affero General Public License as        -->
<!-- published by the Free Software Foundation, either version 3 of the    -->
<!-- License, or (at your option) any later version.                       -->
<!--                                                                       -->
<!-- This program is distributed in the hope that it will be useful, but   -->
<!-- WITHOUT ANY WARRANTY; without even the implied warranty of            -->
<!-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU      -->
<!-- Affero General Public License for more details.                       -->
<!--                                                                       -->
<!-- You should have received a copy of the GNU Affero General Public      -->
<!-- License along with this program. If not, see                          -->
<!-- <http://www.gnu.org/licenses/>.                                       -->
<!--                                                                       -->
<!-- You can be released from the requirements of the license by purchasing-->
<!-- a commercial license. Buying such a license is mandatory as soon as   -->
<!-- you develop activities involving the FlOpEDT/FlOpScheduler software   -->
<!-- without disclosing the source code of your own applications.          -->

{% load static %}

<!DOCTYPE html>
<html lang="fr">
<head>
<style>
</style>
<link rel="stylesheet" href="{% static "base/header.css" %}" />
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=5AeyQYqgW7">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=5AeyQYqgW7">
<link rel="manifest" href="/site.webmanifest?v=5AeyQYqgW7">
<link rel="mask-icon" href="/safari-pinned-tab.svg?v=5AeyQYqgW7" color="#858585">
<link rel="shortcut icon" href="/favicon.ico?v=5AeyQYqgW7">
<meta name="msapplication-TileColor" content="#048c04">
<meta name="theme-color" content="#000000">
<script src="{% static 'base/jquery.min.js' %}"></script>
<script src="{% static 'base/d3.v4.min.js' %}"></script>
<script src="{% static 'base/loader.js' %}"></script>
<script>var url_logo = "{% static 'base/logo-clock.svg' %}";</script>
<!-- script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script -->
<title>{% block title %}Emplois du temps{% endblock %}</title>
</head>
<body>
  <div id="loader" class="loader" style="visibility:hidden;"></div>
<!--<header>Emplois du temps</header>-->
    <nav id="menu-edt">
      <a class="hide_this_link" target="_blank" href="https://framagit.org/flopedt/flopedt" id="live-logo"  style="padding: 0px 0px 0px 0px; float: left">
      </a>
      <div id="full_logo">     
	<span id="acro_logo"> 
	  Fl<span id=opRed >Op</span>EDT<br> 
	</span>
	{% autoescape off %}
	<span id="head_logo">
	  <!--{{ image }}-->
	</span>
	{% endautoescape %}
	<a id="agpl" href="https://www.gnu.org/licenses/agpl-3.0.en.html">
	  <img src="{% static 'base/agplv3-88x31.png'%}" height="31" width="88" alt="AGPL v.3"/>
	</a>
      </div>

       {% block nav %}
       <ul>
	    <li><a href="{% url "base:edt" %}">Consulter</a></li>
	    <li><a href="{% url "base:decale" %}">Décaler/Annuler</a></li>
	    <li><a href="{% url "base:stype" %}">Semaine type</a></li>
	    <li><a href="{% url "base:aide" %}">Aide</a></li>
	    <li><a href="{% url "base:contact" %}">Contact</a></li>
	    {% if user.is_authenticated and user.is_staff %}
	    <li><a href="{% url "solve_board:main_board" %}">Générer</a></li>
	    <li><a href="{% url "admin:index" %}">Admin</a></li>
	    {% endif %}
	    <li style="float:right">{% if user.is_authenticated %}<a href="{% url "people:logout"%}?next={{request.path}}">Déconnexion</a>
	    {% else %}
	    <a href="{% url "people:login"%}?next={{request.path}}">Se connecter</a>
	    {% endif %}
	    </li>
	    <li style="float:right">{% if user.is_authenticated %}
	      <a href="{% url 'people:change_redirect' %}">Connecté&middot;e sous {{ user.username }} </a> {% endif %}
	    </li>
       </ul>
       {% endblock %}
   </nav>
   <section id="content">
       {% block content %}{% endblock %}

   </section>

   <script src="{% static 'base/logo.js' %}";></script>
   <script>
     
   </script>  

</body>
</html>